name: Build Package

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install LLVM
        run: choco install llvm

      - name: Install Ninja
        run: choco install ninja

      - name: Install libclang
        run: pip install libclang

      - name: Download Banjo toolchain
        run: Invoke-WebRequest -OutFile banjo-x86_64-windows.zip https://github.com/chnoblouch/banjo-lang/releases/latest/download/banjo-x86_64-windows.zip

      - name: Extract Banjo toolchain
        run: Expand-Archive .\banjo-x86_64-windows.zip $ENV:USERPROFILE

      - name: Add Banjo toolchain to PATH
        run: echo "$ENV:USERPROFILE\banjo-x86_64-windows\bin" | Out-File -FilePath $ENV:GITHUB_PATH -Encoding utf8 -Append

      - name: Build GLFW
        run: python build_glfw.py
        working-directory: .\scripts

      - name: Upload GLFW build
        uses: actions/upload-artifact@v4
        with:
          name: glfw-x86_64-windows
          path: .\packages\glfw

  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: sudo apt-get install -y ninja-build

      - name: Install build dependencies
        run: sudo apt-get install -y xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules

      - name: Install libclang
        run: pip3 install libclang

      - name: Download Banjo toolchain
        run: curl -OL https://github.com/chnoblouch/banjo-lang/releases/latest/download/banjo-x86_64-linux.zip

      - name: Extract Banjo toolchain
        run: unzip banjo-x86_64-linux.zip -d $HOME
      
      - name: Add Banjo toolchain to PATH
        run: echo "$HOME/banjo-x86_64-linux/bin" >> $GITHUB_PATH

      - name: Build GLFW
        run: python build_glfw.py
        working-directory: ./scripts

      - name: Upload GLFW build
        uses: actions/upload-artifact@v4
        with:
          name: glfw-x86_64-linux
          path: ./packages/glfw
